### ISSUE TITLE
Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture.

### ISSUE THREAD

**Issue by rebrandsoftware** [warcry2000/cordova-plugin-admob-mediation-adcolony#1]
Hi, I'm trying to use this with Phonegap Build and cordova-plugin-admob-free.  However, the iOS build fails with the error "A plugin in your app does not support the compulsory arm64 (64-bit support) architecture.

Here is what it's saying the log:

ld: warning: ignoring file appName/Plugins/cordova-plugin-admob-mediation-adcolony/AdColony.framework/AdColony, file was built for unsupported file format ( 0x58 0x53 0x79 0x6D 0x0A 0x30 0x30 0x32 0x35 0x0A 0x66 0x31 0x36 0x31 0x35 0x31 ) which is not the architecture being linked (arm64): appName/Plugins/cordova-plugin-admob-mediation-adcolony/AdColony.framework/AdColony
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AdColony", referenced from:
      objc-class-ref in libAdapterSDKAdColony.a(GADMAdapterAdColony.o)
      objc-class-ref in libAdapterSDKAdColony.a(GADMAdapterAdColonyInitializer.o)
  "_ADC_SET_USER_GENDER", referenced from:
      -[GADMAdapterAdColony addUserMetadata] in libAdapterSDKAdColony.a(GADMAdapterAdColony.o)
  "_ADC_USER_MALE", referenced from:
      -[GADMAdapterAdColony addUserMetadata] in libAdapterSDKAdColony.a(GADMAdapterAdColony.o)
  "_ADC_SET_USER_LATITUDE", referenced from:
      -[GADMAdapterAdColony addUserMetadata] in libAdapterSDKAdColony.a(GADMAdapterAdColony.o)
  "_ADC_USER_FEMALE", referenced from:
      -[GADMAdapterAdColony addUserMetadata] in libAdapterSDKAdColony.a(GADMAdapterAdColony.o)
  "_ADC_SET_USER_AGE", referenced from:
      -[GADMAdapterAdColony addUserMetadata] in libAdapterSDKAdColony.a(GADMAdapterAdColony.o)
  "_ADC_SET_USER_LONGITUDE", referenced from:
      -[GADMAdapterAdColony addUserMetadata] in libAdapterSDKAdColony.a(GADMAdapterAdColony.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

Any idea what could be causing that?

**Comment by warcry2000** [comment]
Hello,

I had a problem loading the files, not saving them as a link, but as text. I have to see how to raise them well.
cordova-plugin-admob-mediation-adcolony/src/ios/AdColony.framework/AdColony
cordova-plugin-admob-mediation-adcolony/src/ios/AdColony.framework/Headers
cordova-plugin-admob-mediation-adcolony/src/ios/AdColony.framework/Versions/Current

If you replace them with these 3, they are from the original sdk:
https://github.com/AdColony/AdColony-iOS-SDK/tree/master/AdColony.framework/AdColony
https://github.com/AdColony/AdColony-iOS-SDK/tree/master/AdColony.framework/Headers
https://github.com/AdColony/AdColony-iOS-SDK/tree/master/AdColony.framework/Versions/Current

It will work.
Try and tell me.

**Comment by rebrandsoftware** [comment]
Ok, I fixed it and will send a pull request for you soon.

**Comment by rebrandsoftware** [comment]
Scratch that, I guess I'm not authorized.  If you make me a collaborator (or whatever authentication I need to send you a pull request from a branch) I will upload the changes to the SDK files and send a pull request.  All I had to do was copy the SDK files on a mac.

**Comment by warcry2000** [comment]
Hello @rebrandsoftware , I have already invited you to be a collaborator.

**Comment by rebrandsoftware** [comment]
Thanks.  A bit new at this.  :)

**Comment by warcry2000** [comment]
@rebrandsoftware Thanks.

I need to include in plist, which I will do as soon as I can prove it in ios:

<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
    <key>NSAllowsArbitraryLoadsInWebContent</key>
    <true/>
</dict>

<key>LSApplicationQueriesSchemes</key>
    <array>
        <string>fb</string>
        <string>instagram</string>
        <string>tumblr</string>
        <string>twitter</string>
    </array>
</key>

<key>NSCalendarsUsageDescription</key>
<string>Adding events</string>
<key>NSMotionUsageDescription </key>
<string>Interactive ad controls</string>

**Comment by rebrandsoftware** [comment]
After working on this repository yesterday I decided to create another mediation plugin for InMobi: https://github.com/rebrandsoftware/cordova-plugin-admob-mediation-inmobi

I had to do the plist thing too.  Check it out if you want, it's in plugin.xml and I *think* I did it right.  :)

**Comment by warcry2000** [comment]
@rebrandsoftware  Thank you very much, when I have the mac I look at it, and I prove it.

**Comment by rebrandsoftware** [comment]
Just want to let you know that today I've fixed a problem with the adapter in my inMobi plugin linked above and tested both of our plugins in iOS and Android.  They're both working great, so now I can count on at least two mediation sources (AdColony and InMobi) for AdMob Reward Videos.  Thanks for your work on this!
