### ISSUE TITLE
iOS app rejected after adding this plugin

### ISSUE THREAD

**Issue by moldstadt** [warcry2000/cordova-plugin-admob-mediation-adcolony#3]
After adding this plugin, my iOS app gets rejected when I try upload it to iTunes Connect because of missing NSCalendarsUsageDescription.  I didn't have this issue until I added this plugin.  Apparently this was a problem with an older version of Admob SDK and [the required permission was removed in version 7.11.0](https://firebase.google.com/docs/admob/release-notes).  I don't have the problem when I use the AdMob plugin, only when I use the AdColony mediation plugin.

**Comment by warcry2000** [comment]
@moldstadt you need to include in plist:

<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
    <key>NSAllowsArbitraryLoadsInWebContent</key>
    <true/>
</dict>

<key>LSApplicationQueriesSchemes</key>
    <array>
        <string>fb</string>
        <string>instagram</string>
        <string>tumblr</string>
        <string>twitter</string>
    </array>
</key>

<key>NSCalendarsUsageDescription</key>
<string>Adding events</string>
<key>NSMotionUsageDescription </key>
<string>Interactive ad controls</string>
